name: CI

on:
  push:
    branches: [ '**' ]  # Run on all branch pushes
  pull_request:
    branches: [ '**' ]  # Run on all pull requests
  workflow_dispatch:    # Allow manual triggering

jobs:
  go-test:
    name: Go Build & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Show environment
        run: |
          go version
          gcc --version || true

      - name: Build
        run: go build ./...

      - name: Run unit tests
        run: go test ./...

  